spring:
  datasource:
    url: jdbc:mysql://39.105.193.79:3306/company?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT%2B8&autoReconnect=true&failOverReadOnly=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
      #指明连接是否被空闲连接回收器(如果有)进行检验，如果检测失败，则连接将被从池中去除
    testWhileIdle: true
      #在空闲连接回收器线程运行期间休眠的时间值,以毫秒为单位，一般比minEvictableIdleTimeMillis小
    timeBetweenEvictionRunsMillis: 300000
      #在每次空闲连接回收器线程(如果有)运行时检查的连接数量，最好和maxActive一致
    numTestsPerEvictionRun: 50
      #连接池中连接，在时间段内一直空闲，被逐出连接池的时间(1000*60*60)，以毫秒为单位
    minEvictableIdleTimeMillis: 3600000
      #   配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,logback
    maxPoolPreparedStatementPerConnectionSize: 25
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
    #thymeleaf
  thymeleaf:
    prefix: classpath:/templates/
    cache: false
    #信息国际化
  messages:
    basename: i18n.login
server:
  # 服务http端口
  port: 8080
  # tomcat配置
  tomcat:
    # 最大线程数
    max-threads: 6
    # 最小线程数
    min-spare-threads: 3
    # 队列长度
    accept-count: 10
    # 最大链接数
    max-connections: 1000
    #链接建立超时时间
  connection-timeout: 10000






